apiVersion: v1
kind: Service
metadata:
  name: project2-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: project2
    app.kubernetes.io/instance: project2
    app.kubernetes.io/component: service
  ports:
    - port: 80
      targetPort: 80
      name: http
